#!/bin/bash
# RAW URL BASE
BASE="https://raw.githubusercontent.com/kingakesh732-jpg/neopro/main"

clear
echo -e "\e[1;31m   _  _  ____  _____  ____  _       ____  _____  _____"
echo -e "  | \| || ___||  _  ||  _ \| |     / _  ||_   _||___  |"
echo -e "  |    || ___|| |_| ||  __/| |___ | |_| |  | |   |___  |"
echo -e "  |_|\_||____||_____||_|   |_____||_| |_|  |_|  |_____|\e[0m"
echo -e "\e[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "           \e[1;32mMade By - NeoPlayz\e[0m"
echo -e "\e[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "\e[1;31mA) Panel\e[0m"
echo -e "\e[1;31mB) Vps Maker\e[0m"
echo -e "\e[1;31mC) Tools\e[0m"
echo -e "\e[1;31mE) Exit\e[0m"
echo -e "\e[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
read -p "Select → " main_opt

case $main_opt in
    A|a) bash <(curl -sL $BASE/panel.sh) ;;
    B|b) bash <(curl -sL $BASE/vps_maker.sh) ;;
    C|c) bash <(curl -sL $BASE/tools.sh) ;;
    E|e) exit ;;
    *) bash <(curl -sL $BASE/vps) ;;
esac
